import 'package:flutter/material.dart';

List<Tab> tabs = <Tab>[
  const Tab(text: 'All'),
  const Tab(text: 'Activism'),
  const Tab(text: 'Addiction Support'),
  const Tab(text: 'Animal and Pets'),
  const Tab(text: 'Anim'),
  const Tab(text: 'Art'),
  const Tab(text: 'Beauty and Makeup'),
  const Tab(text: 'Business,Economics, and Financ'),
  const Tab(text: 'Career'),
  const Tab(text: 'Cars and Motor Vehicles'),
  const Tab(text: 'Celebrity'),
  const Tab(text: 'Crafts and DIY'),
  const Tab(text: 'Crypto'),
  const Tab(text: 'Culture,Race, and Ethnicit'),
  const Tab(text: 'ُEthics and Philosophy'),
  const Tab(text: 'Family and Relationship'),
  const Tab(text: 'Fashion'),
  const Tab(text: 'Fitness and Nutrition'),
  const Tab(text: 'Food and Drink'),
  const Tab(text: 'Funny/Humor'),
  const Tab(text: 'Gaming'),
  const Tab(text: 'Gender'),
  const Tab(text: 'History'),
  const Tab(text: 'Hobbies'),
  const Tab(text: 'Home and Garden'),
  const Tab(text: 'Internet Culture and Meme'),
  const Tab(text: 'Law'),
  const Tab(text: 'Learning and Education'),
  const Tab(text: 'Marketplace and Deals'),
  const Tab(text: 'Mature Themes and Adult Content'),
  const Tab(text: 'Medical and Mental Health'),
  const Tab(text: 'Men\'s Health'),
  const Tab(text: 'Meta/Reddit'),
  const Tab(text: 'Military'),
  const Tab(text: 'Movies'),
  const Tab(text: 'Music'),
  const Tab(text: 'Outdoors and Nature'),
  const Tab(text: 'Place'),
  const Tab(text: 'Podcasts and Streamers'),
  const Tab(text: 'Politice'),
  const Tab(text: 'Programming'),
  const Tab(text: 'Reading, Writing, and Literature'),
  const Tab(text: 'Religion and Spiritualit'),
  const Tab(text: 'Science'),
  const Tab(text: 'Sexual Orientation'),
  const Tab(text: 'Sport'),
  const Tab(text: 'Tabletop Games'),
  const Tab(text: 'Technology'),
  const Tab(text: 'Television'),
  const Tab(text: 'Trauma Support'),
  const Tab(text: 'Travel'),
  const Tab(text: 'Women\'s Health'),
  const Tab(text: 'World News'),
];
