const topicsName = {
  'Activism',
  'Addiction Support',
  'Animal and Pets',
  'Anime',
  'Art',
  'Beauty and Makeup',
  'Business,Economics, and Finance',
  'Careers',
  'Cars and Motor Vehicles',
  'Celebrity',
  'Crafts and DIY',
  'Crypto',
  'Culture,Race, and Ethnicity',
  'ُEthics and Philosophy',
  'Family and Relationships',
  'Fashion',
  'Fitness and Nutrition',
  'Food and Drink',
  'Funny/Humor',
  'Gaming',
  'Gender',
  'History',
  'Hobbies',
  'Home and Garden',
  'Internet Culture and Memes',
  'Law',
  'Learning and Education',
  'Marketplace and Deals',
  'Mature Themes and Adult Content',
  'Medical and Mental Health',
  'Men\'s Health',
  'Meta/Reddit',
  'Military',
  'Movies',
  'Music',
  'Outdoors and Nature',
  'Place',
  'Podcasts and Streamers',
  'Politics',
  'Programming',
  'Reading, Writing, and Literature',
  'Religion and Spirituality',
  'Science',
  'Sexual Orientation',
  'Sports',
  'Tabletop Games',
  'Technology',
  'Television',
  'Trauma Support',
  'Travel',
  'Women\'s Health',
  'World News',
  'None of these topics',
};
