class Topics {
  final _topics = {
    'Activism': 'assets/img/Activism.png',
    'Addiction Support': 'assets/img/Activism.png',
    'Animal and Pets': 'assets/img/Activism.png',
    'Anime': 'assets/img/Activism.png',
    'Art': 'assets/img/Activism.png',
    'Beauty and Makeup': 'assets/img/Activism.png',
    'Business,Economics, and Finance': 'assets/img/Activism.png',
    'Careers': 'assets/img/Activism.png',
    'Cars and Motor Vehicles': 'assets/img/Activism.png',
    'Celebrity': 'assets/img/Activism.png',
    'Crafts and DIY': 'assets/img/Activism.png',
    'Crypto': 'assets/img/Activism.png',
    'Culture,Race, and Ethnicity': 'assets/img/Activism.png',
    'Family and Relationships': 'assets/img/Activism.png',
    'Fashion': 'assets/img/Activism.png',
    'Fitness and Nutrition': 'assets/img/Activism.png',
    'Food and Drink': 'assets/img/Activism.png',
    'Funny/Humor': 'assets/img/Activism.png',
    'Gaming': 'assets/img/Activism.png',
    'Gender': 'assets/img/Activism.png',
    'History': 'assets/img/Activism.png',
    'Hobbies': 'assets/img/Activism.png',
    'Home and Garden': 'assets/img/Activism.png',
    'Internet Culture and Memes': 'assets/img/Activism.png',
    'Law': 'assets/img/Activism.png',
    'Learning and Education': 'assets/img/Activism.png',
    'Marketplace and Deals': 'assets/img/Activism.png',
    'Mature Themes and Adult Content': 'assets/img/Activism.png',
    'Medical and Mental Health': 'assets/img/Activism.png',
    'Men\'s Health': 'assets/img/Activism.png',
    'Meta/Reddit': 'assets/img/Activism.png',
    'Military': 'assets/img/Activism.png',
    'Movies': 'assets/img/Activism.png',
    'Music': 'assets/img/Activism.png',
    'Outdoors and Nature': 'assets/img/Activism.png',
    'Place': 'assets/img/Activism.png',
    'Podcasts and Streamers': 'assets/img/Activism.png',
    'Politics': 'assets/img/Activism.png',
    'Programming': 'assets/img/Activism.png',
    'Reading, Writing, and Literature': 'assets/img/Activism.png',
    'Religion and Spirituality': 'assets/img/Activism.png',
    'Science': 'assets/img/Activism.png',
    'Sexual Orientation': 'assets/img/Activism.png',
    'Sports': 'assets/img/Activism.png',
    'Tabletop Games': 'assets/img/Activism.png',
    'Technology': 'assets/img/Activism.png',
    'Television': 'assets/img/Activism.png',
    'Trauma Support': 'assets/img/Activism.png',
    'Travel': 'assets/img/Activism.png',
    'Women\'s Health': 'assets/img/Activism.png',
    'World News': 'assets/img/Activism.png',
    'None of these topics': 'assets/img/Activism.png',
  };

  Map<String, dynamic> get topic {
    return {..._topics};
  }
}
