class Topics {
  final _topics = {
    'Activism': 'assets/images/megaphone.png',
    'Addiction Support': 'assets/images/pink-ribbon.png',
    'Animal and Pets': 'assets/images/cat.png',
    'Anime': 'assets/images/otaku.png',
    'Art': 'assets/images/brush.png',
    'Beauty and Makeup': 'assets/images/nail-polish.png',
    'Business,Economics, and Finance': 'assets/images/stats.png',
    'Careers': 'assets/images/gear.png',
    'Cars and Motor Vehicles': 'assets/images/steering-wheel.png',
    'Celebrity': 'assets/images/sun-glasses.png',
    'Crafts and DIY': 'assets/images/paint-roller.png',
    'Crypto': 'assets/images/molecule.png',
    'Culture,Race, and Ethnicity': 'assets/images/link.png',
    'ُEthics and Philosophy': 'assets/images/corporate.png',
    'Family and Relationships': 'assets/images/baby.png',
    'Fashion': 'assets/images/clothes-hanger.png',
    'Fitness and Nutrition': 'assets/images/shoe.png',
    'Food and Drink': 'assets/images/fork.png',
    'Funny/Humor': 'assets/images/happy-face.png',
    'Gaming': 'assets/images/joystick.png',
    'Gender': 'assets/images/gender.png',
    'History': 'assets/images/waiting.png',
    'Hobbies': 'assets/images/car.png',
    'Home and Garden': 'assets/images/plant.png',
    'Internet Culture and Memes': 'assets/images/cursor.png',
    'Law': 'assets/images/balance.png',
    'Learning and Education': 'assets/images/machine-learning.png',
    'Marketplace and Deals': 'assets/images/shopping-bag.png',
    'Mature Themes and Adult Content': 'assets/images/-18.png',
    'Medical and Mental Health': 'assets/images/first-aid-bag.png',
    'Men\'s Health': 'assets/images/masculine.png',
    'Meta/Reddit': 'assets/images/alien-ship.png',
    'Military': 'assets/images/rank.png',
    'Movies': 'assets/images/clapperboard.png',
    'Music': 'assets/images/headphones.png',
    'Outdoors and Nature': 'assets/images/tree.png',
    'Place': 'assets/images/pin.png',
    'Podcasts and Streamers': 'assets/images/podcasts.png',
    'Politics': 'assets/images/court.png',
    'Programming': 'assets/images/keyboard.png',
    'Reading, Writing, and Literature': 'assets/images/book.png',
    'Religion and Spirituality': 'assets/images/koran.png',
    'Science': 'assets/images/flask.png',
    'Sexual Orientation': 'assets/images/rainbow.png',
    'Sports': 'assets/images/ball.png',
    'Tabletop Games': 'assets/images/strategy.png',
    'Technology': 'assets/images/cpu.png',
    'Television': 'assets/images/tv.png',
    'Trauma Support': 'assets/images/love.png',
    'Travel': 'assets/images/airplane.png',
    'Women\'s Health': 'assets/images/femenine.png',
    'World News': 'assets/images/newspaper.png',
    'None of these topics': 'assets/images/atom.png',
  };

  Map<String, dynamic> get topic {
    return {..._topics};
  }
}
