/// Flutter icons ArrowHeadDownWard
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ArrowHeadDownWard
///      fonts:
///       - asset: fonts/ArrowHeadDownWard.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class ArrowHeadDownWard {
  ArrowHeadDownWard._();

  static const _kFontFam = 'ArrowHeadDownWard';
  static const String? _kFontPkg = null;

  static const IconData down_open_mini = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open_big = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
