/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class RedditIcons {
  RedditIcons._();

  static const _kFontFam = 'RedditIcons';
  static const String? _kFontPkg = null;

  static const IconData reddit =
      IconData(0xf1a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit_squared =
      IconData(0xf1a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit_alien =
      IconData(0xf281, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
